# favicon 网站图标
favicon: /img/dh_logo.png

# rss
rss: /atom.xml

# main menu navigation 你还可以添加自己的页面
menu:
  Home: / || 主页
  Tags: /tags/ || 标签
  Categories: /categories/ || 分类
  Archives: /archives/ || 归档
  About: /about/ || 关于
# pagename: /dir/ || 在博客菜单栏显示的名称

bio:
  清者自清，浊者自浊。

avatar: /img/bkico-modified.webp

page_404:
  enable: true
  subtitle: 'Oops! Page not found.'

comments:
  enable: false
  type: waline # waline | valine
  button: true

# Waline https://waline.js.org
waline:
  serverURL: # your waline serverURLs
  avatarCDN: # default is https://sdn.geekzu.org/avatar/
  avatar: monsterid # gravatar style https://zh-tw.gravatar.com/site/implement/images/#default-image
  placeholder: 'Let me know what you think！'

valine:
  appid: # leancloud application app id
  appkey: # leancloud application app key
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  recordIP: false # record IP
  serverURLs: # your serverURLs
  emojiCDN: # emoji CDN
  enableQQ: true

# stylesheets loaded in the <head>
stylesheets:
- /css/main.css

# scripts loaded in the end of the body
scripts:
- /js/main.js
