# Hexo 配置
## 文档: https://hexo.io/zh-cn/docs/configuration.html
## 来源: https://github.com/hexojs/hexo/

# 网站
title: 休闲の小窝
subtitle: '清者自清，浊者自浊'
description: '生活随笔'
keywords:
  - 游戏服务器
  - 技术分享
  - 生活随笔
  - 个人博客
  - 休闲の小窝
  - Hexo
author: kabaka
language: zh-CN # 网站语言
timezone: ''    # 网站时区。Hexo 默认使用您电脑的时区。

# URL
## 在此处设置您网站的网址。例如，如果您使用 GitHub Page，则设置为 'https://username.github.io/project'
url: https://blog.kabaka.xyz # 网址
permalink: posts/:abbrlink/ # 文章的永久链接格式
permalink_defaults:         # 永久链接的默认值
pretty_urls:
  trailing_index: true # 设置为 false 以从永久链接中删除末尾的 'index.html'
  trailing_html: true # 设置为 false 以从永久链接中删除末尾的 '.html'
abbrlink:
  alg: crc32  # 算法可选 crc16（默认）或 crc32
  rep: hex    # 进制可选 dec（默认）或 hex

# 目录
source_dir: source    # 源文件夹，您的内容（文章等）存放的地方
public_dir: public    # 公共文件夹，生成的静态文件存放的地方
tag_dir: tags         # 标签目录
archive_dir: archives # 归档目录
category_dir: categories # 分类目录
code_dir: downloads/code # 代码下载目录
i18n_dir: :lang       # 国际化 (i18n) 目录
skip_render:          # 跳过渲染的文件或文件夹路径。支持通配符。

# 写作
new_post_name: :title.md # 新文章的文件名格式
default_layout: post    # 新文章的默认布局
titlecase: false # 将标题转换为标题格式 (首字母大写)
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site  # 应用范围：site（整个站点）或 post（仅文章）
  exclude: ''  # 不应用此规则的域名列表
filename_case: 0 # 文件名大小写转换: 0 (无转换), 1 (小写), 2 (大写)
render_drafts: false # 是否渲染草稿
post_asset_folder: false # 是否为每篇文章创建一个资源文件夹
relative_link: false # 是否将链接转换为相对于根目录的路径
future: true # 是否显示未来的文章
syntax_highlighter: highlight.js # 语法高亮器: highlight.js 或 prism.js
highlight:
  line_number: true  # 是否显示行号
  auto_detect: false # 是否自动检测语言
  tab_replace: ''    # 将制表符替换为空格数，留空则不替换
  wrap: true         # 是否自动换行
  hljs: false        # 是否使用 highlight.js 自带的样式（如果为 false，则主题需要提供样式）
prismjs:
  preprocess: true   # 是否对代码块进行预处理
  line_number: true  # 是否显示行号
  tab_replace: ''    # 将制表符替换为空格数

# 主页设置
# path: 您博客首页的根路径。(默认 = '')
# per_page: 每页显示的文章数。(0 = 禁用分页)
# order_by: 文章排序方式。(默认按日期降序排列)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类和标签
default_category: uncategorized # 默认分类名称
category_map:                 # 分类别名映射
tag_map:                      # 标签别名映射

# 元数据元素
## https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/meta
meta_generator: true # 是否在头部添加 Hexo generator meta 标签

# 日期/时间格式
## Hexo 使用 Moment.js 来解析和显示日期
## 您可以按照 Moment.js 的定义自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD # 日期格式
time_format: HH:mm:ss   # 时间格式
## updated_option 支持 'mtime'（文件修改时间）, 'date'（front-matter中的日期）, 'empty'（不显示更新时间）
updated_option: 'mtime'

# 分页
## 将 per_page 设置为 0 以禁用分页
per_page: 10       # 每页显示的文章数。0 表示禁用分页。
pagination_dir: page # 分页目录

# 包含/排除文件
## include:/exclude: 选项仅适用于 'source/' 文件夹
include:
exclude:
ignore:

# 扩展
## 插件: https://hexo.io/zh-cn/plugins/
## 主题: https://hexo.io/zh-cn/themes/
#theme: landscape # 默认主题
theme: butterfly   # 当前使用的主题

# 部署
## 文档: https://hexo.io/zh-cn/docs/one-command-deployment
deploy:
  type: '' # 部署类型，例如 git, heroku, rsync 等

nofollow:
  enable: true # 是否为外部链接添加 rel="nofollow"
  exclude:     # 不添加 nofollow 的域名列表
    - blog.kabaka.xyz  # 排除自身域名或友链
all_minifier: true